/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AuthRouteRouteImport } from "./routes/auth/route"
import { Route as appRouteRouteImport } from "./routes/(app)/route"
import { Route as AuthIndexRouteImport } from "./routes/auth/index"
import { Route as appIndexRouteImport } from "./routes/(app)/index"
import { Route as AuthSsoCallbackRouteImport } from "./routes/auth/sso-callback"
import { Route as AuthRegisterRouteImport } from "./routes/auth/register"
import { Route as AuthLoginRouteImport } from "./routes/auth/login"
import { Route as appProfileRouteImport } from "./routes/(app)/profile"
import { Route as appNotesRouteImport } from "./routes/(app)/notes"
import { Route as appConversationsRouteRouteImport } from "./routes/(app)/conversations/route"
import { Route as appSoilsIndexRouteImport } from "./routes/(app)/soils/index"
import { Route as appConversationsIndexRouteImport } from "./routes/(app)/conversations/index"
import { Route as appSoilsCreateRouteImport } from "./routes/(app)/soils/create"
import { Route as appConversationsSessionIdRouteImport } from "./routes/(app)/conversations/$sessionId"
import { Route as appAnalysisCreateRouteImport } from "./routes/(app)/analysis/create"
import { Route as appAnalysisIdRouteImport } from "./routes/(app)/analysis/$id"
import { Route as appSoilsSoilIdIndexRouteImport } from "./routes/(app)/soils/$soilId/index"
import { Route as appSoilsSoilIdEditRouteImport } from "./routes/(app)/soils/$soilId/edit"

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: "/(app)",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appRouteRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: "/sso-callback",
  path: "/sso-callback",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => appRouteRoute,
} as any)
const appNotesRoute = appNotesRouteImport.update({
  id: "/notes",
  path: "/notes",
  getParentRoute: () => appRouteRoute,
} as any)
const appConversationsRouteRoute = appConversationsRouteRouteImport.update({
  id: "/conversations",
  path: "/conversations",
  getParentRoute: () => appRouteRoute,
} as any)
const appSoilsIndexRoute = appSoilsIndexRouteImport.update({
  id: "/soils/",
  path: "/soils/",
  getParentRoute: () => appRouteRoute,
} as any)
const appConversationsIndexRoute = appConversationsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appConversationsRouteRoute,
} as any)
const appSoilsCreateRoute = appSoilsCreateRouteImport.update({
  id: "/soils/create",
  path: "/soils/create",
  getParentRoute: () => appRouteRoute,
} as any)
const appConversationsSessionIdRoute =
  appConversationsSessionIdRouteImport.update({
    id: "/$sessionId",
    path: "/$sessionId",
    getParentRoute: () => appConversationsRouteRoute,
  } as any)
const appAnalysisCreateRoute = appAnalysisCreateRouteImport.update({
  id: "/analysis/create",
  path: "/analysis/create",
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalysisIdRoute = appAnalysisIdRouteImport.update({
  id: "/analysis/$id",
  path: "/analysis/$id",
  getParentRoute: () => appRouteRoute,
} as any)
const appSoilsSoilIdIndexRoute = appSoilsSoilIdIndexRouteImport.update({
  id: "/soils/$soilId/",
  path: "/soils/$soilId/",
  getParentRoute: () => appRouteRoute,
} as any)
const appSoilsSoilIdEditRoute = appSoilsSoilIdEditRouteImport.update({
  id: "/soils/$soilId/edit",
  path: "/soils/$soilId/edit",
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/auth": typeof AuthRouteRouteWithChildren
  "/conversations": typeof appConversationsRouteRouteWithChildren
  "/notes": typeof appNotesRoute
  "/profile": typeof appProfileRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/sso-callback": typeof AuthSsoCallbackRoute
  "/": typeof appIndexRoute
  "/auth/": typeof AuthIndexRoute
  "/analysis/$id": typeof appAnalysisIdRoute
  "/analysis/create": typeof appAnalysisCreateRoute
  "/conversations/$sessionId": typeof appConversationsSessionIdRoute
  "/soils/create": typeof appSoilsCreateRoute
  "/conversations/": typeof appConversationsIndexRoute
  "/soils/": typeof appSoilsIndexRoute
  "/soils/$soilId/edit": typeof appSoilsSoilIdEditRoute
  "/soils/$soilId/": typeof appSoilsSoilIdIndexRoute
}
export interface FileRoutesByTo {
  "/notes": typeof appNotesRoute
  "/profile": typeof appProfileRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/sso-callback": typeof AuthSsoCallbackRoute
  "/": typeof appIndexRoute
  "/auth": typeof AuthIndexRoute
  "/analysis/$id": typeof appAnalysisIdRoute
  "/analysis/create": typeof appAnalysisCreateRoute
  "/conversations/$sessionId": typeof appConversationsSessionIdRoute
  "/soils/create": typeof appSoilsCreateRoute
  "/conversations": typeof appConversationsIndexRoute
  "/soils": typeof appSoilsIndexRoute
  "/soils/$soilId/edit": typeof appSoilsSoilIdEditRoute
  "/soils/$soilId": typeof appSoilsSoilIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(app)": typeof appRouteRouteWithChildren
  "/auth": typeof AuthRouteRouteWithChildren
  "/(app)/conversations": typeof appConversationsRouteRouteWithChildren
  "/(app)/notes": typeof appNotesRoute
  "/(app)/profile": typeof appProfileRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/sso-callback": typeof AuthSsoCallbackRoute
  "/(app)/": typeof appIndexRoute
  "/auth/": typeof AuthIndexRoute
  "/(app)/analysis/$id": typeof appAnalysisIdRoute
  "/(app)/analysis/create": typeof appAnalysisCreateRoute
  "/(app)/conversations/$sessionId": typeof appConversationsSessionIdRoute
  "/(app)/soils/create": typeof appSoilsCreateRoute
  "/(app)/conversations/": typeof appConversationsIndexRoute
  "/(app)/soils/": typeof appSoilsIndexRoute
  "/(app)/soils/$soilId/edit": typeof appSoilsSoilIdEditRoute
  "/(app)/soils/$soilId/": typeof appSoilsSoilIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/auth"
    | "/conversations"
    | "/notes"
    | "/profile"
    | "/auth/login"
    | "/auth/register"
    | "/auth/sso-callback"
    | "/"
    | "/auth/"
    | "/analysis/$id"
    | "/analysis/create"
    | "/conversations/$sessionId"
    | "/soils/create"
    | "/conversations/"
    | "/soils/"
    | "/soils/$soilId/edit"
    | "/soils/$soilId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/notes"
    | "/profile"
    | "/auth/login"
    | "/auth/register"
    | "/auth/sso-callback"
    | "/"
    | "/auth"
    | "/analysis/$id"
    | "/analysis/create"
    | "/conversations/$sessionId"
    | "/soils/create"
    | "/conversations"
    | "/soils"
    | "/soils/$soilId/edit"
    | "/soils/$soilId"
  id:
    | "__root__"
    | "/(app)"
    | "/auth"
    | "/(app)/conversations"
    | "/(app)/notes"
    | "/(app)/profile"
    | "/auth/login"
    | "/auth/register"
    | "/auth/sso-callback"
    | "/(app)/"
    | "/auth/"
    | "/(app)/analysis/$id"
    | "/(app)/analysis/create"
    | "/(app)/conversations/$sessionId"
    | "/(app)/soils/create"
    | "/(app)/conversations/"
    | "/(app)/soils/"
    | "/(app)/soils/$soilId/edit"
    | "/(app)/soils/$soilId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)": {
      id: "/(app)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/": {
      id: "/auth/"
      path: "/"
      fullPath: "/auth/"
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/(app)/": {
      id: "/(app)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/auth/sso-callback": {
      id: "/auth/sso-callback"
      path: "/sso-callback"
      fullPath: "/auth/sso-callback"
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/register": {
      id: "/auth/register"
      path: "/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/(app)/profile": {
      id: "/(app)/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/notes": {
      id: "/(app)/notes"
      path: "/notes"
      fullPath: "/notes"
      preLoaderRoute: typeof appNotesRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conversations": {
      id: "/(app)/conversations"
      path: "/conversations"
      fullPath: "/conversations"
      preLoaderRoute: typeof appConversationsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/soils/": {
      id: "/(app)/soils/"
      path: "/soils"
      fullPath: "/soils/"
      preLoaderRoute: typeof appSoilsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conversations/": {
      id: "/(app)/conversations/"
      path: "/"
      fullPath: "/conversations/"
      preLoaderRoute: typeof appConversationsIndexRouteImport
      parentRoute: typeof appConversationsRouteRoute
    }
    "/(app)/soils/create": {
      id: "/(app)/soils/create"
      path: "/soils/create"
      fullPath: "/soils/create"
      preLoaderRoute: typeof appSoilsCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conversations/$sessionId": {
      id: "/(app)/conversations/$sessionId"
      path: "/$sessionId"
      fullPath: "/conversations/$sessionId"
      preLoaderRoute: typeof appConversationsSessionIdRouteImport
      parentRoute: typeof appConversationsRouteRoute
    }
    "/(app)/analysis/create": {
      id: "/(app)/analysis/create"
      path: "/analysis/create"
      fullPath: "/analysis/create"
      preLoaderRoute: typeof appAnalysisCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/analysis/$id": {
      id: "/(app)/analysis/$id"
      path: "/analysis/$id"
      fullPath: "/analysis/$id"
      preLoaderRoute: typeof appAnalysisIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/soils/$soilId/": {
      id: "/(app)/soils/$soilId/"
      path: "/soils/$soilId"
      fullPath: "/soils/$soilId/"
      preLoaderRoute: typeof appSoilsSoilIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/soils/$soilId/edit": {
      id: "/(app)/soils/$soilId/edit"
      path: "/soils/$soilId/edit"
      fullPath: "/soils/$soilId/edit"
      preLoaderRoute: typeof appSoilsSoilIdEditRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appConversationsRouteRouteChildren {
  appConversationsSessionIdRoute: typeof appConversationsSessionIdRoute
  appConversationsIndexRoute: typeof appConversationsIndexRoute
}

const appConversationsRouteRouteChildren: appConversationsRouteRouteChildren = {
  appConversationsSessionIdRoute: appConversationsSessionIdRoute,
  appConversationsIndexRoute: appConversationsIndexRoute,
}

const appConversationsRouteRouteWithChildren =
  appConversationsRouteRoute._addFileChildren(
    appConversationsRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appConversationsRouteRoute: typeof appConversationsRouteRouteWithChildren
  appNotesRoute: typeof appNotesRoute
  appProfileRoute: typeof appProfileRoute
  appIndexRoute: typeof appIndexRoute
  appAnalysisIdRoute: typeof appAnalysisIdRoute
  appAnalysisCreateRoute: typeof appAnalysisCreateRoute
  appSoilsCreateRoute: typeof appSoilsCreateRoute
  appSoilsIndexRoute: typeof appSoilsIndexRoute
  appSoilsSoilIdEditRoute: typeof appSoilsSoilIdEditRoute
  appSoilsSoilIdIndexRoute: typeof appSoilsSoilIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appConversationsRouteRoute: appConversationsRouteRouteWithChildren,
  appNotesRoute: appNotesRoute,
  appProfileRoute: appProfileRoute,
  appIndexRoute: appIndexRoute,
  appAnalysisIdRoute: appAnalysisIdRoute,
  appAnalysisCreateRoute: appAnalysisCreateRoute,
  appSoilsCreateRoute: appSoilsCreateRoute,
  appSoilsIndexRoute: appSoilsIndexRoute,
  appSoilsSoilIdEditRoute: appSoilsSoilIdEditRoute,
  appSoilsSoilIdIndexRoute: appSoilsSoilIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
